version: '2.3'

services:
  loramap:
    build:
      context: .
    image: janniswarnat/loramap:latest
    command: ["mono","./Lora-Map.exe"]
    ports:
      - 8080:8080
    volumes:
      - "./Lora-Map/config/requests.conf:/etc/loramap/requests.conf"
      - "./Lora-Map/config/settings.conf:/etc/loramap/settings.conf"
